services:
  backend:
    build: ./backend
    container_name: django-api
    volumes:
      - ./backend:/app
      - ./backend/db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build: ./frontend
    container_name: react-frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

