# Generated by Django 5.1.7 on 2025-03-09 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ricipe',
            new_name='Recipe',
        ),
    ]
