name: Build and Deploy with Docker Compose

on:
  push:
    branches:
      - main  # Запускать при push в ветку main

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

    
      - name: Build and Push Docker Images
        run: |
          docker-compose -f docker-compose.yml build  
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin  
          docker-compose -f docker-compose.yml push  

  deploy:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no user@your-server << 'EOF'
            cd /path/to/your/project
            git pull origin main
            docker-compose pull
            docker-compose up -d --remove-orphans
          EOF
